default:
#  tags:
#    - docker
#    - dpsd
#    - did
  services:
    - name: docker:29.2.1-dind
      alias: docker
stages:
  - before
#  - build
#  - test
  - release

tag-version:
  stage: before
  artifacts:
    paths:
      - version.txt
  script:
    - DOCKER_TAG_VERSION=$(date +"%Y%m%d%H")
    - echo "DOCKER_TAG_VERSION=$(date +"%Y%m%d%H")" > version.txt
    - echo "Version to use for docker tag $DOCKER_TAG_VERSION"
  rules:
    - if: $CI_COMMIT_TAG  # Run job ONLY if a tag is present (tag push event)
      when: always       # Always run the job when the condition is met

other-version:
  stage: before
  artifacts:
    paths:
      - version.txt
  script:
    - DOCKER_TAG_VERSION=$CI_COMMIT_REF_SLUG
    - echo "DOCKER_TAG_VERSION=$CI_COMMIT_REF_SLUG" > version.txt
    - echo "Version to use for docker tag $DOCKER_TAG_VERSION"
  rules:
    - if: $CI_COMMIT_BRANCH  # Run job ONLY if a tag is present (tag push event)
      when: always       # never run the job when the condition is met

release_job:
  stage: release
  needs:
    - job: other-version
      optional: true
    - job: tag-version
      optional: true
  before_script:
    - apt-get update && apt-get install -y git >/dev/null
    - git config --global user.email ${GITLAB_USER_EMAIL}
    - git config --global user.name ${GITLAB_USER_NAME}
    - git remote set-url origin https://oauth2:${GITLAB_TOKEN}@${CI_PROJECT_URL#https://}.git
  script:
    - echo "Create releas2e"
    - git tag -f $DOCKER_TAG_VERSION
    - git push --tags

#
#build-frontend-dev:
#  stage: build
#  image: node
#  script:
#    - cd raid-agency-app
#    - npm install
#    - npm run build:dev
#  artifacts:
#    paths:
#      - "raid-agency-app/dist/"
#  cache:
#    key: "$CI_PROJECT_ID"
#    policy: pull-push  # Allow this job to update the cache (important as we run npm install here)
#    paths:
#      - raid-agency-app/node_modules/
#
#build-frontend-acc:
#  stage: build
#  image: node
#  script:
#    - cd raid-agency-app
#    - npm install
#    - npm run build:acc
#  artifacts:
#    paths:
#      - "raid-agency-app/dist/"
#  cache:
#    key: "$CI_PROJECT_ID"
#    policy: pull-push  # Allow this job to update the cache (important as we run npm install here)
#    paths:
#      - raid-agency-app/node_modules/
#
#build-frontend-prod:
#  stage: build
#  image: node
#  script:
#    - cd raid-agency-app
#    - npm install
#    - npm run build
#  artifacts:
#    paths:
#      - "raid-agency-app/dist/"
#  cache:
#    key: "$CI_PROJECT_ID"
#    policy: pull-push  # Allow this job to update the cache (important as we run npm install here)
#    paths:
#      - raid-agency-app/node_modules/
#
#docker-frontend-dev:
#  stage: build
#  image: docker:29.2.1-cli
#  dependencies:
#    - other-version
#    - tag-version
#    - build-frontend-dev
#  needs:
#    - build-frontend-dev
#    - job: other-version
#      optional: true
#    - job: tag-version
#      optional: true
#  variables:
#    DOCKER_DRIVER: overlay2
#    DOCKER_BUILDKIT: 1
#    DOCKER_TLS_CERTDIR: ""
#  cache:
#    key: "$CI_PROJECT_ID"
#    policy: pull
#  script:
#    - source version.txt
#    - IMAGE_TAG=$CI_REGISTRY_IMAGE/raid-fe:$DOCKER_TAG_VERSION-dev
#    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
#    - cd raid-agency-app
#    - docker build -t $IMAGE_TAG .
#    - docker push $IMAGE_TAG
#
#docker-frontend-acc:
#  stage: build
#  image: docker:29.2.1-cli
#  dependencies:
#    - other-version
#    - tag-version
#    - build-frontend-acc
#  needs:
#    - build-frontend-acc
#    - job: other-version
#      optional: true
#    - job: tag-version
#      optional: true
#  variables:
#    DOCKER_DRIVER: overlay2
#    DOCKER_BUILDKIT: 1
#    DOCKER_TLS_CERTDIR: ""
#  cache:
#    key: "$CI_PROJECT_ID"
#    policy: pull
#  script:
#    - source version.txt
#    - IMAGE_TAG=$CI_REGISTRY_IMAGE/raid-fe:$DOCKER_TAG_VERSION-acc
#    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
#    - cd raid-agency-app
#    - docker build -t $IMAGE_TAG .
#    - docker push $IMAGE_TAG
#
#docker-frontend-prod:
#  stage: build
#  image: docker:29.2.1-cli
#  dependencies:
#    - other-version
#    - tag-version
#    - build-frontend-prod
#  needs:
#    - build-frontend-prod
#    - job: other-version
#      optional: true
#    - job: tag-version
#      optional: true
#  variables:
#    DOCKER_DRIVER: overlay2
#    DOCKER_BUILDKIT: 1
#    DOCKER_TLS_CERTDIR: ""
#  cache:
#    key: "$CI_PROJECT_ID"
#    policy: pull
#  script:
#    - source version.txt
#    - IMAGE_TAG=$CI_REGISTRY_IMAGE/raid-fe:$DOCKER_TAG_VERSION-prod
#    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
#    - cd raid-agency-app
#    - docker build -t $IMAGE_TAG .
#    - docker push $IMAGE_TAG
##
##test-frontend:
##  stage: test
##  image: node
##  needs:
##    - build-frontend
##  script:
##    - cd raid-agency-app
##    - npm install
##    - npm run test
##    - npm run e2e
##  cache:
##    key: "$CI_PROJECT_ID"
##    policy: pull
#
#build-api:
#  stage: build
#  image: gradle:9.2.1-jdk17-alpine
#  script:
#    - ./gradlew -x test build jar
#  artifacts:
#    paths:
#      - "api-svc/raid-api/build/libs"
#      - "iam/build/libs"
#      - "build/reports"
#
#docker-api:
#  stage: build
#  image: docker:29.2.1-cli
#  dependencies:
#    - other-version
#    - tag-version
#    - build-api
#  needs:
#    - build-api
#    - job: other-version
#      optional: true
#    - job: tag-version
#      optional: true
#  variables:
#    DOCKER_DRIVER: overlay2
#    DOCKER_BUILDKIT: 1
#    DOCKER_TLS_CERTDIR: ""
#  script:
#    - source version.txt
#    - IMAGE_TAG=$CI_REGISTRY_IMAGE/raid-api:$DOCKER_TAG_VERSION
#    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
#    - cd api-svc/raid-api
#    - docker build -t $IMAGE_TAG .
#    - docker push $IMAGE_TAG
#
#test-api:
#  stage: test
#  image: gradle:9.2.1-jdk17-alpine
#  needs:
#    - build-api
#  script:
#    - ./gradlew test
#  artifacts:
#    paths:
#      - "build/reports"
#
#docker-iam:
#  stage: build
#  image: docker:29.2.1-cli
#  dependencies:
#    - other-version
#    - tag-version
#    - build-api
#  needs:
#    - build-api
#    - job: other-version
#      optional: true
#    - job: tag-version
#      optional: true
#  variables:
#    DOCKER_DRIVER: overlay2
#    DOCKER_BUILDKIT: 1
#    DOCKER_TLS_CERTDIR: ""
#  script:
#    - source version.txt
#    - IMAGE_TAG=$CI_REGISTRY_IMAGE/raid-iam:$DOCKER_TAG_VERSION
#    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
#    - cd iam
#    - docker build -t $IMAGE_TAG .
#    - docker push $IMAGE_TAG