default:
  tags:
    - docker
build-frontend:
  stage: build
  image: node
  script:
    - cd raid-agency-app
    - npm install
    - npm run build
  artifacts:
    paths:
      - "raid-agency-app/dist/"
      - "nodes_modules"

test-frontend:
  stage: test
  image: node
  needs:
    - build-frontend
  script:
    - cd raid-agency-app
    - npm run test
    - npm run e2e


build-api:
  stage: build
  image: gradle:7-jdk17-alpine
  script:
    - ./gradlew build
  artifacts:
    paths:
      - "api-svc/raid-api/build/libs"

test-api:
  stage: test
  image: gradle:7-jdk17-alpine
  needs:
    - build-api
  script:
    - ./gradlew test
