raid:
  stub:
    geo-names:
      enabled: true
      delay: 150
    orcid:
      enabled: true
      delay: 150
    apids:
      enabled: true
      delay: 150
    ror:
      enabled: true
      delay: 150
    doi:
      enabled: true
      delay: 150
    open-street-map:
      enabled: true
      delay: 150
  identifier:
    name-prefix: http://raid.local/
    schema-uri: https://raid.org/
    license: Creative Commons CC-0
    landing-prefix: http://localhost:7080/handle
    global-url-prefix: https://hdl.handle.net
    registration-agency-identifier: https://ror.org/038sjwq14
    handle-url-prefix: http://localhost:8080
  db:
    user: postgres
    password: supersecret
    host: localhost
    port: 7432
    name: raido
  spatial-coverage:
    schema-uri:
      geonames: https://www.geonames.org/
      openstreetmap: https://www.openstreetmap.org/
  validation:
    geonames:
      username: geonames
  history:
    baseline-interval: 5
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${raid.db.host}:${raid.db.port}/${raid.db.name}
    username: ${raid.db.user}
    password: ${raid.db.password}
  jooq:
    sql-dialect: postgres
  flyway:
    default-schema: api_svc
    create-schemas: true
    baseline-version: 25
    locations:
      - classpath:db/migration
      - classpath:db/env/api_user
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /docs
datacite:
  endpoint: https://api.test.datacite.org
  prefix: 10.82841
  password: not-set
  user: NPQS.RKFZRK