raid:
  isni-client:
    url-format: https://isni.oclc.org/sru/?query=pica.isn+%3D+%22__ISNI__%22&operation=searchRetrieve&recordSchema=isni-b
  orcid-client:
    base-url: https://api.sandbox.orcid.org/v3.0/
    access-token: not-set
  ror-client:
    client-id: 08VB3D1YYHC63CQ8QHP0TBD0I6RULCHQ
    base-url: https://api.ror.org/v2/
  orcid-integration:
    orcid-url-prefix: https://sandbox.orcid.org/
    host: http://localhost:1080
    raid-listener:
      uri: ${raid.orcid-integration.host}/raid-update
    contributor-email-lookup:
      uri: ${raid.orcid-integration.host}/find-contributor-by-email
    contributor-id-lookup:
      uri: ${raid.orcid-integration.host}/find-contributor-by-orcid
  stub:
    geo-names:
      enabled: true
      delay: 150
    orcid:
      enabled: true
      delay: 150
    apids:
      enabled: true
      delay: 150
    ror:
      enabled: true
      delay: 150
    doi:
      enabled: true
      delay: 150
    open-street-map:
      enabled: true
      delay: 150
  identifier:
    schema-uri: https://raid.org/
    license: Creative Commons CC-0
    landing-prefix: https://raid.org/
    global-url-prefix: https://hdl.handle.net
    registration-agency-identifier: https://ror.org/038sjwq14
    handle-url-prefix: https://static.test.raid.org.au/
  spatial-coverage:
    schema-uri:
      geonames: https://www.geonames.org/
      openstreetmap: https://www.openstreetmap.org/
  validation:
    geonames:
      username: geonames
  history:
    baseline-interval: 50
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${raid.db.host}:${raid.db.port}/${raid.db.name}
    username: ${raid.db.user}
    password: ${raid.db.password}
  jooq:
    sql-dialect: postgres
  flyway:
    default-schema: api_svc
    create-schemas: true
    baseline-version: 25
  security:
    oauth2:
      resourceserver:
        jwt:
            issuer-uri: ${raid.iam.realm-uri}
      client:
        registration:
          keycloak:
            client-id: raid-api-2
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: ${raid.iam.realm-uri}
            user-name-attribute: preferred_username
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    path: /docs
datacite:
  endpoint: https://api.test.datacite.org/dois
  registration-agency-name: Australian Research Data Commons