raid:
  identifier:
    name-prefix: http://localhost:8080/
  db:
    user: postgres
    password: supersecret
    host: localhost
    port: 7432
    name: raido_prod
    encryption-key: pB7MB3iuYmmjWMTOCK6HS0JetzWhCtBtKoNl39pBr3Q=
  iam:
    realm-uri: http://localhost:8001/realms/raid
  raid-permissions:
    client-id: raid-permissions-admin
    client-secret: 07ATOSG9hYs8oATcz5wcQAdRuoEsLzEY
spring:
  flyway:
    locations: classpath:db/env/api_user,classpath:db/migration,classpath:db/env/prod
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-secret: Nr0HycAztrRSNehq9EZR2wKvqmpC3JfS
datacite:
  endpoint: http://localhost:1080/dois