http://doi.org/|http://doi.org/
http://hdl.handle.net/|http://hdl.handle.net/
https://archive.org/|https://archive.org/
https://arks.org/|https://arks.org/
https://scicrunch.org/resolver/|https://scicrunch.org/resolver/
https://www.isbn-international.org/|https://www.isbn-international.org/