-- Renumber Service Points into the block allocated to this Registration Agency.
--
-- service_point.id has started at a hardcoded 20000000 on every instance, and is
-- published in RAiD metadata as identifier.owner.servicePoint, so two agencies
-- could mint Service Points that are indistinguishable in federated metadata.
--
-- ${servicePointIdStart} and ${servicePointIdBlockSize} are supplied by
-- ServicePointIdRangeConfig, which derives them from the agency's own ROR. An
-- agency with no allocated block fails before this migration runs, so the
-- placeholders are always resolved by the time we get here.
--
-- Everything below runs in one transaction: a failure leaves the database exactly
-- as it was rather than committing a half-applied renumbering.

-- Children follow their parent instead of being updated by hand. raid_archive is
-- the exception: V41 created it without a foreign key, so it is updated below.
alter table app_user
    drop constraint app_user_service_point_id_fkey,
    add constraint app_user_service_point_id_fkey
        foreign key (service_point_id) references service_point (id) on update cascade;

alter table raid
    drop constraint raid_service_point_id_fkey,
    add constraint raid_service_point_id_fkey
        foreign key (service_point_id) references service_point (id) on update cascade;

alter table user_authz_request
    drop constraint user_authz_request_service_point_id_fkey,
    add constraint user_authz_request_service_point_id_fkey
        foreign key (service_point_id) references service_point (id) on update cascade;

-- A GENERATED ALWAYS identity column rejects UPDATE outright ("column can only be
-- updated to DEFAULT"), so it is relaxed for the renumbering and restored after.
alter table service_point
    alter column id set generated by default;

do
$$
    declare
        v_start  bigint := ${servicePointIdStart};
        v_block  bigint := ${servicePointIdBlockSize};
        v_min    bigint;
        v_max    bigint;
        v_offset bigint;
        v_missed bigint;
    begin
        select min(id), max(id) into v_min, v_max from service_point;

        if v_min is null then
            raise notice 'No Service Points to renumber; sequence will start at %', v_start;
            return;
        end if;

        if v_min >= v_start and v_max < v_start + v_block then
            raise notice 'Service Points % to % are already within the allocated block; nothing to renumber',
                v_min, v_max;
            return;
        end if;

        -- Anchor the lowest id at the start of the block. Differences between ids
        -- are preserved, so existing gaps survive and referenced values stay
        -- consistent. Blocks are far enough apart that the source and target
        -- ranges never overlap, so a single statement cannot collide on the
        -- primary key.
        v_offset := v_start - v_min;

        raise notice 'Renumbering % Service Points by % into block starting at %',
            (select count(*) from service_point), v_offset, v_start;

        update service_point set id = id + v_offset;

        -- No foreign key, so the cascade above does not reach it.
        update raid_archive
        set service_point_id = service_point_id + v_offset;

        -- The id is also embedded in each stored RAiD document.
        update raid
        set metadata = jsonb_set(
                metadata,
                '{identifier,owner,servicePoint}',
                to_jsonb((metadata -> 'identifier' -> 'owner' ->> 'servicePoint')::bigint + v_offset))
        where metadata -> 'identifier' -> 'owner' ? 'servicePoint';

        update raid_archive
        set metadata = jsonb_set(
                metadata,
                '{identifier,owner,servicePoint}',
                to_jsonb((metadata -> 'identifier' -> 'owner' ->> 'servicePoint')::bigint + v_offset))
        where metadata -> 'identifier' -> 'owner' ? 'servicePoint';

        -- raid_history holds the JSON Patch documents that RaidHistoryService
        -- replays to reconstruct a RaidDto, and that reconstruction backs the
        -- single-raid GET, the edit form and the update checksum. The id is
        -- embedded in those patches too, so leaving them alone would make the
        -- detail view disagree with the list view and would break updates,
        -- which look the Service Point up by the id the patches carry.
        --
        -- diff is text rather than jsonb and holds an array of operations, so
        -- this rebuilds each array rather than setting a fixed path. The id can
        -- sit at three depths depending on how much of the document a given
        -- revision rewrote, and op is not part of the match because add and
        -- replace need identical treatment.
        update raid_history
        set diff = (select jsonb_agg(
                                   case
                                       when element ->> 'path' = '/identifier/owner/servicePoint'
                                           and jsonb_typeof(element -> 'value') = 'number'
                                           then jsonb_set(element, '{value}',
                                                          to_jsonb((element ->> 'value')::bigint + v_offset))
                                       when element ->> 'path' = '/identifier/owner'
                                           and element -> 'value' ? 'servicePoint'
                                           then jsonb_set(element, '{value,servicePoint}',
                                                          to_jsonb((element -> 'value' ->> 'servicePoint')::bigint +
                                                                   v_offset))
                                       when element ->> 'path' = '/identifier'
                                           and element -> 'value' -> 'owner' ? 'servicePoint'
                                           then jsonb_set(element, '{value,owner,servicePoint}',
                                                          to_jsonb((element -> 'value' -> 'owner' ->> 'servicePoint')::bigint +
                                                                   v_offset))
                                       else element
                                       end
                                   order by ordinality)::text
                    from jsonb_array_elements(diff::jsonb) with ordinality as patch(element, ordinality))
        where jsonb_typeof(diff::jsonb) = 'array'
          and diff like '%servicePoint%';

        -- No foreign key protects these patches, so assert the rewrite reached every
        -- one. A patch that was missed still carries a pre-renumbering id, which is
        -- recognisable because adding the offset again lands on a Service Point that
        -- now exists. Patches referencing a Service Point that was already gone are
        -- left out by the same test, since nothing they point at exists either way.
        select count(*)
        into v_missed
        from raid_history h,
             lateral jsonb_array_elements(h.diff::jsonb) as element
        where jsonb_typeof(h.diff::jsonb) = 'array'
          and exists (select 1
                      from service_point sp
                      where sp.id = case
                                        when element ->> 'path' = '/identifier/owner/servicePoint'
                                            and jsonb_typeof(element -> 'value') = 'number'
                                            then (element ->> 'value')::bigint + v_offset
                                        when element ->> 'path' = '/identifier/owner'
                                            then (element -> 'value' ->> 'servicePoint')::bigint + v_offset
                                        when element ->> 'path' = '/identifier'
                                            then (element -> 'value' -> 'owner' ->> 'servicePoint')::bigint + v_offset
                          end);

        if v_missed > 0 then
            raise exception 'Renumbering left % raid_history patches carrying a pre-renumbering Service Point',
                v_missed;
        end if;
    end
$$;

alter table service_point
    alter column id set generated always;

-- Continue from the renumbered ids, or seed a fresh instance at its block start.
do
$$
    declare
        v_next bigint;
    begin
        select coalesce(max(id) + 1, ${servicePointIdStart}) into v_next from service_point;
        execute format('alter table service_point alter column id restart with %s', v_next);
    end
$$;

-- Adding the constraint validates every existing row, so this both prevents future
-- out-of-block inserts and asserts that the renumbering above landed correctly. A
-- failure here rolls the whole migration back.
--
-- Reallocating an agency's block later requires a migration to drop and recreate
-- this constraint.
alter table service_point
    add constraint service_point_id_within_allocated_block
        check (id >= ${servicePointIdStart}
            and id < ${servicePointIdStart} + ${servicePointIdBlockSize});

-- The cascade and the explicit updates above are only correct if every referencing
-- row still points at a Service Point, and if no stored document disagrees with the
-- row it belongs to.
do
$$
    declare
        v_orphans    bigint;
        v_mismatched bigint;
    begin
        select count(*) into v_orphans from raid_archive a
        where not exists (select 1 from service_point sp where sp.id = a.service_point_id);

        if v_orphans > 0 then
            raise exception 'Renumbering left % raid_archive rows referencing a Service Point that does not exist',
                v_orphans;
        end if;

        select count(*) into v_mismatched from raid
        where metadata -> 'identifier' -> 'owner' ? 'servicePoint'
          and (metadata -> 'identifier' -> 'owner' ->> 'servicePoint')::bigint <> service_point_id;

        if v_mismatched > 0 then
            raise exception 'Renumbering left % raid rows whose metadata servicePoint disagrees with service_point_id',
                v_mismatched;
        end if;
    end
$$;
