site_name: RAiD metadata model
theme:
  name: material
docs_dir: generated/v2/docs
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
extra:
  version:
    provider: mike
    default: 2.0.0