site_name: RAiD metadata model
theme:
  name: material
docs_dir: v2/generated/docs
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  