site_name: RAiD metadata schema
theme:
  name: material
  features:
    - navigation.expand 
    - navigation.path
docs_dir: generated/v2/schema-docs
plugins:
  - search
  - awesome-nav
markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format    