openapi: 3.0.3
info:
  title: stable-api-endpoints
  version: 1.0.0
  description: >
    The first metadata schema supported by Raido.
    The stuff in this "raido-metadata" file is "Raido" specific, as compared to
    the more standard "Raid" stuff defined in the "raid-metadata" file.
    This is what all raids imported from the legacy application were imported
    as.
paths:
  /raid/v1:
    post:
      tags:
        - basic-raid-stable
      operationId: create-raid-v1
      summary: mint a raid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - { $ref: 'components.yaml#/components/schemas/RaidSchemaV1' }
              required: [ metadataSchema, titles, dates, contributors, access ]
      responses:
        200:
          description: The Raid was successfully created.
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/RaidSchemaV1'
        400:
          description: There was a problem with the message sent to the server.
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/ValidationFailureResponse'
    get:
      tags:
        - basic-raid-stable
      operationId: list-raids-v1
      summary: list raids
      parameters:
        - name: servicePointId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'components.yaml#/components/schemas/RaidSchemaV1'
  /raid/v1/{prefix}/{suffix}:
    parameters:
      - name: prefix
        in: path
        required: true
        description: Prefix of the raid handle
        schema:
          type: string
      - name: suffix
        in: path
        required: true
        description: Suffix of the raid handle
        schema:
          type: string
    get:
      tags:
        - basic-raid-stable
      operationId: read-raid-v1
      summary: read a raid, caller must be authorized
      responses:
        200:
          description: data
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/RaidSchemaV1'
    put:
      tags:
        - basic-raid-stable
      operationId: update-raid-v1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - { $ref: 'components.yaml#/components/schemas/RaidSchemaV1' }
              required: [ id, metadataSchema, titles, dates, contributors, access ]
      responses:
        200:
          description: The Raid was successfully updated.
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/RaidSchemaV1'
        400:
          description: Bad request. There was a problem with the message sent to the server.
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/ValidationFailureResponse'