openapi: 3.0.3
info:
  title: raid listing and minting endpoints
  version: 1.0.0
paths:
  /list-raid:          
    post:
      tags:
        - basic-raid-experimental
      operationId: list-raid
      summary: list raids
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RaidListRequest'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RaidListItemV1'
  /mint-raid-v1:          
    post:
      tags:
        - basic-raid-experimental
      operationId: mint-raid-v1
      summary: mint a raid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MintRaidRequestV1'
      responses:
        '200':
          description: data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaidListItemV1'
  /update-raid-v1:          
    post:
      tags:
        - basic-raid-experimental
      operationId: update-raid-v1
      summary: mint a raid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MintRaidRequestV1'
      responses:
        '200':
          description: data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MintRaidRequestV1'
  /read-raid-v1:          
    post:
      tags:
        - basic-raid-experimental
      operationId: read-raid-v1
      summary: read a raid
      # going with post, because I think we are gonna get complex with this
      # eventually (specifying what we want to read, graphql-style).
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [handle]
              properties:
                handle: {type: string}
      responses:
        '200':
          description: data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MintRaidRequestV1'

components:
  schemas:
    RaidListRequest:
      type: object
      required: [servicePointId]
      properties:
        servicePointId: {$ref: 'shared.yaml#/components/schemas/SurrogateKey' }
        name: {type: string}
    MintRaidRequestV1:
      type: object
      required: [handle, servicePointId, name]
      properties:
        handle: {type: string}
        servicePointId: {$ref: 'shared.yaml#/components/schemas/SurrogateKey' }
        name: {type: string}
        startDate: { type: string, format: date-time }
        metadataEnvelopeSchema: {type: string}
        metadata: {type: object}
    RaidListItemV1:
      type: object
      required: [handle]
      properties:
        handle: {type: string}
        name: {type: string}
        startDate: { type: string, format: date }
