openapi: 3.0.3
info:
  title: shared types
  version: 1.0.0
  description: >
    This file contains types that are broadly shared across the API.
    It is not expected to contain any endpoints.
paths:

components:
  schemas:
    RaidSchemaV1:
      type: object
      properties:
        id: { $ref: 'metadata-block.yaml#/components/schemas/IdBlock' }
        metadataSchema: { $ref: 'shared.yaml#/components/schemas/RaidoMetaschema' }
        titles:
          type: array
          items: { $ref: 'metadata-block.yaml#/components/schemas/TitleBlock' }
        dates: { $ref: 'metadata-block.yaml#/components/schemas/DatesBlock' }
        descriptions:
          type: array
          items: { $ref: 'metadata-block.yaml#/components/schemas/DescriptionBlock' }
        access: { $ref: 'metadata-block.yaml#/components/schemas/AccessBlock' }
        alternateUrls:
          type: array
          items: { $ref: 'metadata-block.yaml#/components/schemas/AlternateUrlBlock' }
        contributors:
          type: array
          items: { $ref: 'metadata-contributor-block.yaml#/components/schemas/ContributorBlock' }
        organisations:
          type: array
          items: { $ref: 'metadata-organisation-block.yaml#/components/schemas/OrganisationBlock' }
        subjects:
          type: array
          items: { $ref: 'metadata-block.yaml#/components/schemas/SubjectBlock' }
        relatedRaids:
          type: array
          items: { $ref: 'metadata-block.yaml#/components/schemas/RelatedRaidBlock' }
        relatedObjects:
          type: array
          items: { $ref: 'metadata-block.yaml#/components/schemas/RelatedObjectBlock' }

    ErrorResponse:
      type: object
      required: [type, title, status]
      properties:
        type: { type: string }
        title: { type: string }
    FailureResponse:
      type: object
      required: [type, title, status, detail, instance]
      properties:
        type: { type: string }
        title: { type: string }
        status: {type: integer }
        detail: { type: string }
        instance: { type: string }
    ValidationFailureResponse:
      allOf:
        - $ref: '#/components/schemas/FailureResponse'
      required: [failures]
      properties:
        failures:
          type: array
          items:
            $ref: 'shared.yaml#/components/schemas/ValidationFailure'

