openapi: 3.0.3
info:
  title: public endpoints
  description: >
    Contains all the end points that can called anonymously.
    Including the API endpoint that produces data for the public 
    "landing page".
  version: 1.0.0
paths:
  /version:
    get:
      security: []
      tags:
        - public-experimental
      operationId: version
      summary: get info about server
      responses:
        '200':
          description: version info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResult'
  /public-list-service-point:
    get:
      security: []
      tags:
        - public-experimental
      operationId: public-list-service-point
      summary: list service point data that un-authn users can see
      description: >
        Returns only enabled service-points - intended for use on the 
        authz-request page.  Note that it is not paginated nor does it have a 
        limit on the number of records it returns.  May need to be refactored
        to something more scalable in future, if we ever have a lot of 
        service-points. 
      responses:
        '200':
          description: public service-point data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicServicePoint'
  /public-read-raid-v3:
    get:
      security: []
      tags:
        - public-experimental
      operationId: public-read-raid-v3
      summary: >
        read raid data
      parameters:
        - in: path
          name: handle
          schema: { type: string }
          required: true
          description: handle
      responses:
        '200':
          description: result of request
          content:
            application/json:
              schema:
                $ref: 'raid-metadata-schema.yaml#/components/schemas/PublicReadRaidResponseV3'

components:
  schemas:
    VersionResult:
      type: object
      properties:
        buildVersion: {type: string}
        buildCommitId: {type: string}
        buildDate: { type: string }
        startDate: { type: string, format: date-time }
    PublicServicePoint:
      description: data that non-authn users can see (do not leak email)
      type: object
      required: [id, name]
      properties:
        id: {$ref: 'shared.yaml#/components/schemas/SurrogateKey' }
        name: {type: string}
    PublicReadRaidResponseV2:
      type: object
      required: [
        handle, metadata, createDate, ]
      properties:
        handle: { type: string }
        servicePointId: { $ref: 'shared.yaml#/components/schemas/SurrogateKey' }
        servicePointName: { type: string }
        createDate: { type: string, format: date-time }
        metadata: { type: object }
