openapi: 3.0.3
info:
  title: public endpoints
  description: >
    Contains end points that can called anonymously.
    Including the API endpoint that produces data for the public 
    "landing page".
  version: 1.0.0
paths:

  /public-api-get-raid:
    get:
      security: []
      tags:
        - public-stable
      operationId: public-api-get-raid
      summary: >
        read publicly visible raid data, note that closed raids are mapped as
        PublicClosedMetadataSchemaV1
      parameters:
        - in: path
          name: prefix
          schema: { type: string }
          required: true
          description: handle prefix
        - in: path
          name: suffix
          schema: { type: string }
          required: true
          description: handle suffix
      responses:
        '200':
          description: response including raid metadata
          content:
            application/json:
              schema:
                $ref: 'raid-metadata-schema.yaml#/components/schemas/PublicReadRaidResponseV3'

