openapi: 3.0.3
info:
  title: raid listing and minting endpoints
  version: 1.0.0
paths:
  /version:
    get:
      security: []
      tags:
        - public-experimental
      operationId: version
      summary: get info about server
      responses:
        '200':
          description: version info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionResult'
  /list-public-service-point:
    get:
      security: []
      tags:
        - public-experimental
      operationId: list-public-service-point
      summary: list service point data that un-authn users can see
      responses:
        '200':
          description: public service-point data
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicServicePoint'
  /update-request-authz:
    post:
      tags:
        - public-experimental
      operationId: update-request-authz
      summary: create or update an authz request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthzRequest'
      responses:
        '200':
          description: result of request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateAuthzResponse'


components:
  schemas:
    VersionResult:
      type: object
      properties:
        buildVersion: {type: string}
        buildCommitId: {type: string}
        buildDate: { type: string }
        startDate: { type: string, format: date-time }
    PublicServicePoint:
      description: data that non-authn users can see (do not leak email)
      type: object
      required: [id, name]
      properties:
        id: {$ref: 'shared.yaml#/components/schemas/SurrogateKey' }
        name: {type: string}
    UpdateAuthzRequest:
      description: authorization request
      type: object
      required: [servicePointId, name]
      properties:
        servicePointId: {$ref: 'shared.yaml#/components/schemas/SurrogateKey' }
        comments: {type: string}
    # would be nice to do an "any-of" type spec that generates an enum on the 
    # TS side - not sure OAS spec and the tooling supports it yet?
    UpdateAuthzResponse:
      type: object
      required: [status]
      properties:
        status: {
          $ref: 'admin-experimental.yaml#/components/schemas/AuthzRequestStatus'
        }
