openapi: 3.0.3
info:
  title: stable-api-endpoints
  version: 1.0.0
  description: >
    The first metadata schema supported by Raido.
    The stuff in this "raido-metadata" file is "Raido" specific, as compared to
    the more standard "Raid" stuff defined in the "raid-metadata" file.
    This is what all raids imported from the legacy application were imported
    as.
paths:
  /raid:
    post:
      tags:
        - raido-stable-v1
      operationId: create-raid-v1
      summary: mint a raid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - { $ref: '#/components/schemas/RaidDto' }
              required: [ metadataSchema, titles, dates, contributors, access ]
      responses:
        200:
          description: The Raid was successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaidDto'
        400:
          description: There was a problem with the message sent to the server.
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/ValidationFailureResponse'
    get:
      tags:
        - raido-stable-v1
      operationId: list-raids-v1
      summary: list raids
      parameters:
        - name: servicePointId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RaidDto'
  /raid/{prefix}/{suffix}:
    parameters:
      - name: prefix
        in: path
        required: true
        description: Prefix of the raid handle
        schema:
          type: string
      - name: suffix
        in: path
        required: true
        description: Suffix of the raid handle
        schema:
          type: string
    get:
      tags:
        - raido-stable-v1
      operationId: read-raid-v1
      summary: read a raid, caller must be authorized
      responses:
        200:
          description: data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaidDto'
    put:
      tags:
        - raido-stable-v1
      operationId: update-raid-v1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              allOf:
                - { $ref: '#/components/schemas/RaidDto' }
              required: [ id, metadataSchema, titles, dates, contributors, access ]
      responses:
        200:
          description: The Raid was successfully updated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RaidDto'
        400:
          description: Bad request. There was a problem with the message sent to the server.
          content:
            application/json:
              schema:
                $ref: 'components.yaml#/components/schemas/ValidationFailureResponse'
components:
  schemas:
    RaidDto:
      type: object
      properties:
        id: { $ref: '#/components/schemas/Id' }
        titles:
          type: array
          items: { $ref: '#/components/schemas/Title' }
        dates: { $ref: '#/components/schemas/Dates' }
        descriptions:
          type: array
          items: { $ref: '#/components/schemas/Description' }
        access: { $ref: '#/components/schemas/Access' }
        alternateUrls:
          type: array
          items: { $ref: '#/components/schemas/AlternateUrl' }
        contributors:
          type: array
          items: { $ref: '#/components/schemas/Contributor' }
        organisations:
          type: array
          items: { $ref: '#/components/schemas/Organisation' }
        subjects:
          type: array
          items: { $ref: '#/components/schemas/Subject' }
        relatedRaids:
          type: array
          items: { $ref: '#/components/schemas/RelatedRaid' }
        relatedObjects:
          type: array
          items: { $ref: '#/components/schemas/RelatedObject' }
        alternateIdentifiers:
          type: array
          items: { $ref: '#/components/schemas/AlternateIdentifier' }
        spatialCoverages:
          type: array
          items: { $ref: '#/components/schemas/SpatialCoverage' }
        traditionalKnowledgeLabels:
          type: array
          items: { $ref: '#/components/schemas/TraditionalKnowledgeLabel' }
    Id:
      type: object
      required: [ id, schemaUri, registrationAgency, owner, servicePoint, version ]
      properties:
        id:
          type: string
          description: The identifier of the raid, e.g. https://raid.org.au/102.100.100/zzz
          example: https://raid.org/xxx.yyy/zzz
        schemaUri:
          type: string
          description: >
            The URI of the Identifier scheme. For example, https://raid.org
          example: https://raid.org
        registrationAgency:
          $ref: '#/components/schemas/RegistrationAgency'
        owner:
          $ref: '#/components/schemas/Owner'
        servicePoint:
          type: integer
          format: int64
          description: >
            The Service Point that requested the RAiD. Analogous to a DataCite ‘Repository’. ‘Owners’ can have multiple
            Service Points, and SPs do not need to be legal entities.
          example: 20000003
        globalUrl:
          type: string
          description: >
            The URL for the raid via the CNRI handle system, e.g 
            https://hdl.handle.net/xxx.yyy/zzz
          example: https://hdl.handle.net/xxx.yyy/zzz
        raidAgencyUrl:
          type: string
          description: >
            The URL for the raid via the minting raid agency system, e.g 
            https://raid.org.au/10378.1/1695863
          example: https://demo.raido-infra.com/handle/10378.1/1695863
        version:
          type: integer
          description: The version of the resource. Read-only. Increments automatically on update.
    RegistrationAgency:
      type: object
      description: >
        ROR that identifies the organisation that operates the raid registration agency software that minted this raid.
      required: [id, schemaUri]
      properties:
        id: {
          type: string,
          example: https://ror.org/02stey378
        }
        schemaUri: {
          type: string,
          example: https://ror.org
        }
    Owner:
      type: object
      description: >
        The legal entity responsible for the RAiD; the ‘Owner’ of a RAiD. Analogous to a DataCite ‘Member’, has a 
        legal agreement with the Registration Agency.
      required: [id, schemaUri]
      properties:
        id: {
          type: string,
          example: https://ror.org/02stey378
        }
        schemaUri: {
          type: string,
          example: https://ror.org
        }
    Dates:
      type: object
      required: [ "startDate" ]
      properties:
        startDate: { type: string, format: date }
        endDate: { type: string, format: date }
    Title:
      type: object
      required: [title, type, startDate]
      properties:
        title: {type: string}
        type:
          $ref: '#/components/schemas/TitleTypeWithSchemaUri'
        startDate: { type: string, format: date }
        endDate: { type: string, format: date }
        language:
          $ref: '#/components/schemas/Language'
    TitleTypeWithSchemaUri:
      type: object
      properties:
        id: {
          type: string,
          example: https://github.com/au-research/raid-metadata/blob/main/scheme/title/type/v1/primary.json
        }
        schemaUri: {
          type: string,
          example: https://github.com/au-research/raid-metadata/tree/main/scheme/title/type/v1
        }
    Description:
      type: object
      required: ["description", "type"]
      properties:
        description: {type: string}
        type:
          $ref: '#/components/schemas/DescriptionTypeWithSchemaUri'
        language:
          $ref: '#/components/schemas/Language'
    DescriptionTypeWithSchemaUri:
      type: object
      required: [id, schemaUri]
      properties:
        id: {
          type: string,
          example: https://github.com/au-research/raid-metadata/blob/main/scheme/description/type/v1/primary.json
        }
        schemaUri: {
           type: string,
           example: https://github.com/au-research/raid-metadata/tree/main/scheme/description/type/v1
        }
    Access:
      type: object
      required: ["type"]
      properties:
        type:
          $ref: '#/components/schemas/AccessTypeWithSchemaUri'
        accessStatement:
          $ref: '#/components/schemas/AccessStatement'
        embargoExpiry: {
          type: string,
          format: date
        }
    AccessStatement:
      type: object
      required: [statement]
      properties:
        statement: { type: string }
        language:
          $ref: '#/components/schemas/Language'
    AccessTypeWithSchemaUri:
      type: object
      required: [ id, schemaUri ]
      properties:
        id: {
          type: string,
          example: https://github.com/au-research/raid-metadata/blob/main/scheme/access/type/v1/open.json
        }
        schemaUri: {
          type: string,
          example: https://github.com/au-research/raid-metadata/tree/main/scheme/access/type/v1
        }
    Contributor:
      type: object
      required: [id, schemaUri, positions, roles]
      properties:
        id:
          type: string
        schemaUri: {
          type: string,
          example: https://orcid.org/
        }
        positions:
          type: array
          items:
            $ref: '#/components/schemas/ContributorPositionWithSchemaUri'
        roles:
          type: array
          items:
            $ref: '#/components/schemas/ContributorRoleWithSchemaUri'
    ContributorPositionWithSchemaUri:
      type: object
      required: [ schemaUri, id, startDate ]
      properties:
        schemaUri: {
          type: string,
          example: https://github.com/au-research/raid-metadata/tree/main/scheme/contributor/position/v1
        }
        id: {
          type: string,
          example: https://github.com/au-research/raid-metadata/blob/main/scheme/contributor/position/v1/leader.json
        }
        startDate: {
          type: string
        }
        endDate: {
          type: string
        }
    ContributorRoleWithSchemaUri:
      type: object
      required: [ id, schemaUri ]
      properties:
        schemaUri: {
          type: string,
          example: https://credit.niso.org/
        }
        id: {
          type: string,
          example: https://credit.niso.org/contributor-roles/writing-review-editing/
        }
    Organisation:
      type: object
      required: [id, schemaUri, roles]
      properties:
        id: { type: string }
        schemaUri: {
          type: string,
          example: https://ror.org/
        }
        roles:
          type: array
          items:
            $ref: '#/components/schemas/OrganisationRoleWithSchemaUri'
    OrganisationRoleWithSchemaUri:
      type: object
      required: [id, schemaUri, startDate]
      properties:
        schemaUri: {
          type: string,
          example: https://github.com/au-research/raid-metadata/tree/main/scheme/organisation/role/v1
        }
        id: {
          type: string,
          example: https://github.com/au-research/raid-metadata/blob/main/scheme/organisation/role/v1/lead-research-organisation.json
        }
        startDate: { type: string, format: date }
        endDate: { type: string, format: date }
    AlternateUrl:
      type: object
      required: [ "url", ]
      properties:
        url: { type: string }
    Subject:
      type: object
      required: [ id, schemaUri ]
      properties:
        id: { type: string }
        schemaUri: { type: string }
        keywords:
          type: array
          items:
            $ref: '#/components/schemas/SubjectKeyword'
    SubjectKeyword:
      type: object
      required: [ keyword ]
      properties:
        keyword: { type: string }
        language:
          $ref: '#/components/schemas/Language'
    RelatedRaid:
      type: object
      properties:
        id: { type: string }
        type:
          $ref: '#/components/schemas/RelatedRaidType'
    RelatedRaidType:
      type: object
      required: [ id, schemaUri ]
      properties:
        id: {
          type: string,
          example: https://github.com/au-research/raid-metadata/blob/main/scheme/related-raid/type/v1/continues.json
        }
        schemaUri: {
          type: string,
          example: https://github.com/au-research/raid-metadata/tree/main/scheme/related-raid/type/v1
        }
    RelatedObject:
      type: object
      properties:
        id: { type: string }
        schemaUri: { type: string }
        type:
          $ref: '#/components/schemas/RelatedObjectType'
        category:
          $ref: '#/components/schemas/RelatedObjectCategory'
    RelatedObjectType:
      type: object
      properties:
        id: {
          type: string,
          example: https://github.com/au-research/raid-metadata/blob/main/scheme/related-object/type/v1/book.json
        }
        schemaUri: {
          type: string,
          example: https://github.com/au-research/raid-metadata/tree/main/scheme/related-object/type/v1
        }
    RelatedObjectCategory:
      type: object
      properties:
        id: {
          type: string,
          example: https://github.com/au-research/raid-metadata/blob/main/scheme/related-object/category/v1/input.json
        }
        schemaUri: {
          type: string,
          example: https://github.com/au-research/raid-metadata/tree/main/scheme/related-object/category/v1
        }
    AlternateIdentifier:
        type: object
        properties:
          id: { type: string }
          type: { type: string }
    SpatialCoverage:
      type: object
      properties:
        id: { type: string }
        schemaUri: { type: string }
        place: { type: string }
        language:
          $ref: '#/components/schemas/Language'
    TraditionalKnowledgeLabel:
      type: object
      properties:
        schemaUri: { type: string }
    Language:
      type: object
      required: [ code, schemaUri]
      properties:
        id: {
          type: string,
          example: eng
        }
        schemaUri: {
          type: string,
          example: https://iso639-3.sil.org/
        }