openapi: 3.0.1
servers:
  - url: 'https://demo.raido-infra.com'
info:
  title: RAID v2 API
  version: 2.0.0
  contact:
    name: ASDC RAiD team
    email: web.services@ardc.edu.au
tags:
  - name: public-experimental
    description: The APIs are not stable, they may change at any time.  
      Can be called without auth.
    
paths:
  /v2/public/version:
    get:
      tags:
        - public-experimental
      operationId: version
      summary: get info about server
      responses:
        '200':
          description: version info
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/versionResult'
  /v2/public/institution:
    get:
      tags:
        - public-experimental
      operationId: list-institutions
      summary: list institutions
      responses:
        '200':
          description: institutions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/institution'

components:
  schemas:
    versionResult:
      type: object
      properties:
        buildVersion: {type: string}
        buildCommitId: {type: string}
        buildDate: { type: string }
        startDate: { type: string, format: date-time }
    institution:
      type: object
      properties:
        id: {type: string}
        name: {type: string}
          


