openapi: 3.0.3
info:
  title: stable-api-endpoints
  version: 1.0.0
  description: >
    The first metadata schema supported by Raido.
    The stuff in this "raido-metadata" file is "Raido" specific, as compared to
    the more standard "Raid" stuff defined in the "raid-metadata" file.
    This is what all raids imported from the legacy application were imported
    as.
paths:
  /service-point:
    post:
      security:
        bearerAuth: [ ]
      tags:
        operationId: create
        summary: Create a service point
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref:
components:
  schemas:
    ServicePointCreateRequest:

