openapi: 3.0.3
info:
  title: Service Point API
  version: 1.0.0
  description: >
    Endpoints for service point and team management
paths:
  /service-point:
    post:
      security:
        - bearerAuth: [ ]
      tags:
        - service-point
      operationId: createServicePoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/ServicePointCreateRequest'
      responses:
        201:
          description: The service point was successfully created.
          content:
            application/json:
              schema:
                $ref: 'shared.yaml#/components/schemas/ServicePoint'
        400:
          description: There was a problem with the message sent to the server.
          content:
            application/json:
              schema:
                $ref: 'shared.yaml#/components/schemas/ValidationFailureResponse'
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - service-point
      operationId: findAllServicePoints
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'shared.yaml#/components/schemas/ServicePoint'
  /service-point/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: The id of the service point
        schema:
          type: integer
          format: int64
    get:
      security:
        - bearerAuth: [ ]
      tags:
        - service-point
      operationId: findServicePointById
      responses:
        200:
          description: data
          content:
            application/json:
              schema:
                $ref: 'shared.yaml#/components/schemas/ServicePoint'
    put:
      security:
        - bearerAuth: [ ]
      tags:
        - service-point
      operationId: updateServicePoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/ServicePointUpdateRequest'
      responses:
        200:
          description: The service point was successfully updated.
          content:
            application/json:
              schema:
                $ref: 'shared.yaml#/components/schemas/ServicePoint'
        400:
          description: Bad request. There was a problem with the message sent to the server.
          content:
            application/json:
              schema:
                $ref: 'shared.yaml#/components/schemas/ValidationFailureResponse'
components:
  schemas:
    ServicePointCreateRequest:
      type: object
      required:
        - name
        - identifierOwner
      properties:
        name:
          type: string
          description: The name of the service point
          example: Australian Research Data Commons
        adminEmail:
          type: string
          description: The email address of the person responsible for administering the service point.
        techEmail:
          type: string
          description: The email address of a technical contact when using the API
        identifierOwner:
          type: string
          description: The PID of the institution that will own the RAiDs (currently only RORs are supported).
          example: https://ror.org/038sjwq14
        repositoryId:
          type: string
          description: The Datacite repository id. This needs to be created in Fabrica.
          example: VBGR.QJYTRX
        prefix:
          type: string
          description: The prefix used in the handle when minting RAiDs. Assigned when the repository is created.
          example: 10.82481
        password:
          type: string
          description: The password of the repository in Datacite.
        appWritesEnabled:
          type: boolean
          description: Whether users are able to edit RAiDs in the in the app. This can cause conflicts when also creating/updating RAiDs through the API.
        enabled:
          type: boolean
          description: Whether the service point is able to create or update RAiDs
    ServicePointUpdateRequest:
      allOf:
        - $ref: '#/components/schemas/ServicePointCreateRequest'
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          description: The name of the service point
          example: Australian Research Data Commons