openapi: 3.0.3
info:
  title: shared types
  version: 1.0.0
  description: >
    This file contains types that are broadly shared across the API.
    It is not expected to contain any endpoints.
paths:
  
components:
  schemas:
    SurrogateKey: { type: integer, format: int64}
    ValidationFailure:
      type: object
      required: [fieldId, errorType, message]
      properties:
        fieldId: { type: string }
        errorType: { type: string }
        message: { type: string }
    RaidoMetaschema:
      description: >
        "Metaschema" is the enumeration of different "Metadata schema" 
        that Raido supports.
        The values are currently match the discriminator type names used for
        returning metadata, but they don't have to. 
      type: string
      enum: ['RaidoMetadataSchemaV1', 'LegacyMetadataSchemaV1']
    RaidoMetaschemaV2:
      description: >
        "Metaschema" is the enumeration of different "Metadata schema" 
        that Raido supports.
        The values are currently match the discriminator type names used for
        returning metadata, but they don't have to.
      type: string
      enum: ['RaidoMetadataSchemaV2', 'RaidoMetadataSchemaV1', 'LegacyMetadataSchemaV1']
    SchemaVersion:
      description: >
        "Metaschema" is the enumeration of different "Metadata schema" 
        that Raido supports.
        The values are currently match the discriminator type names used for
        returning metadata, but they don't have to.
      type: string

    
