openapi: 3.0.3
info:
  title: shared types
  version: 1.0.0
  description: >
    This file contains types that are broadly shared across the API.
    It is not expected to contain any endpoints.
paths:
  
components:
  schemas:
    SurrogateKey:
      type: integer
      format: int64
    ValidationFailure:
      type: object
      required: [ fieldId, errorType, message ]
      properties:
        fieldId: { type: string }
        errorType: { type: string }
        message: { type: string }
    FailureResponse:
      type: object
      required: [ type, title, status, detail, instance ]
      properties:
        type: { type: string }
        title: { type: string }
        status: { type: integer }
        detail: { type: string }
        instance: { type: string }
    ValidationFailureResponse:
      allOf:
        - $ref: '#/components/schemas/FailureResponse'
      required: [ failures ]
      properties:
        failures:
          type: array
          items:
            $ref: '#/components/schemas/ValidationFailure'
    ServicePoint:
      description: data that any member of service-point and operators can see
      type: object
      required: [id, name, identifierOwner, adminEmail, techEmail, enabled]
      properties:
        id: {$ref: 'shared.yaml#/components/schemas/SurrogateKey' }
        name: {type: string}
        identifierOwner: { type: string }
        repositoryId:
          type: string
          description: The Datacite repository id. This needs to be created in Fabrica.
          example: VBGR.QJYTRX
        prefix:
          type: string
          description: The prefix used in the handle when minting RAiDs. Assigned when the repository is created.
          example: 10.82481
        password:
          type: string
          description: The password of the repository in Datacite.
        searchContent: {type: string}
        techEmail: {type: string}
        adminEmail: {type: string}
        enabled: {type: boolean}
        appWritesEnabled: { type: boolean }