openapi: 3.0.3
info:
  title: unapproved-experimental 
  description: >
    Endpoints that are expected to be called after authenticating via OAuth2, 
    but before the user has been approved to use the system.
    The client must provide a bearer token of type `UnapprovedUserApiToken`, 
    which is returned from the authentication process for users who have not
    been approved.
    See https://github.com/au-research/raido/tree/6fe43e756c3f91eb75a0f2b208cbcd67dfbfd1e0/api-svc/spring/src/main/java/raido/apisvc/endpoint/auth
    See https://github.com/au-research/raido/blob/main/doc/security/access-control/authorization/unapproved-user-authz-request-flow.md
  version: 1.0.0
  termsOfService: https://github.com/au-research/raido/blob/main/doc/service-level-guide.md
paths:
  /update-authz-request:
    post:
      tags:
        - unapproved-experimental
      operationId: update-authz-request
      summary: create or update an authz-request
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateAuthzRequest'
      responses:
        '200':
          description: result of request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UpdateAuthzResponse'

components:
  schemas:
    UpdateAuthzRequest:
      type: object
      required: [servicePointId, name]
      properties:
        servicePointId: {$ref: 'shared.yaml#/components/schemas/SurrogateKey' }
        comments: {type: string}
    UpdateAuthzResponse:
      type: object
      required: [status]
      properties:
        status: {
          $ref: 'admin-experimental.yaml#/components/schemas/AuthzRequestStatus'
        }
        authzRequestId:
          allOf:
            - $ref: 'shared.yaml#/components/schemas/SurrogateKey'
            - description: > 
                May be empty if the authz-request is "auto-approved", in which
                case no authz-request was created because the the app-user has 
                already been approved and added to the system.  When the 
                auto-approved user logs in again, they will be able
                to use the system.