raid:
  iam:
    base-url: http://localhost:8001
  stub:
    geo-names:
      enabled: true
      delay: 150
    orcid:
      enabled: true
      delay: 150
    apids:
      enabled: true
      delay: 150
    ror:
      enabled: true
      delay: 150
    doi:
      enabled: true
      delay: 150
    open-street-map:
      enabled: true
      delay: 150
  identifier:
    name-prefix: http://raid.local/
    license: Creative Commons CC-0
    landing-prefix: http://localhost:7080/handle
    global-url-prefix: https://hdl.handle.net
    registration-agency-identifier: https://ror.org/038sjwq14
    handle-url-prefix: http://localhost:8080
    schema-uri: https://raid.org/
  test:
    api:
      url: http://localhost:${server.port}
      raid-au-user-token: not-set
      uq-admin-token: not-set
    auth:
      base-url: ${raid.iam.base-url}/realms/raid
      client-id: raid-api
      grant-type: password
      token-uri: ${raid.test.auth.base-url}/protocol/openid-connect/token
      admin:
        user: raid-au-group-admin
        password: password
      raid-au:
        user: raid-test-user
        password: password
      uq:
        user: uq-test-user
        password: password
      raid-admin:
        user: raid-admin
        password: password
      raid-user:
        user: raid-user
        password: password
      integration-test-client:
        client-id: integration-test-client
        client-secret: ee3qpd47IurMdOlmdPTEdCG6Ib2zPjUN
  db:
    user: postgres
    password: supersecret
    host: localhost
    port: 7432
  spatial-coverage:
    schema-uri:
      geonames: https://www.geonames.org/
      openstreetmap: https://www.openstreetmap.org/
  validation:
    geonames:
      username: geonames
  history:
    baseline-interval: 5
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${raid.db.host}:${raid.db.port}/raido
    username: ${raid.db.user}
    password: ${raid.db.password}
  jooq:
    sql-dialect: postgres
  flyway:
    enabled: false
server:
  port: 8080
