raid:
  identifier:
    name-prefix: http://raid.local/
    license: Creative Commons CC-0
    landing-prefix: http://localhost:7080/handle
    global-url-prefix: https://hdl.handle.net
    registration-agency-identifier: https://ror.org/038sjwq14
    handle-url-prefix: http://localhost:8080
    schema-uri: https://raid.org/
  test:
    api:
      url: http://localhost:${server.port}
  db:
    user: postgres
    password: changeme
    host: localhost
    port: 7432
  spatial-coverage:
    schema-uri:
      geonames: https://www.geonames.org/
      openstreetmap: https://www.openstreetmap.org/
  validation:
    geonames:
      username: geonames
  history:
    baseline-interval: 5
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${raid.db.host}:${raid.db.port}/raido
    username: ${raid.db.user}
    password: ${raid.db.password}
  jooq:
    sql-dialect: postgres
  flyway:
    enabled: false
server:
  port: 8080