version: '3.4'
services:
  keycloak:
    container_name: keycloak
    image: raid-keycloak:20240612.0
    ports:
      - 8000:8443
      - 8001:8080
      - 9000:9000
    command: ['start-dev', '--import-realm', '--debug']
    volumes:
      - './realms:/opt/keycloak/data/import'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_SCHEMA: public
      KC_HOSTNAME_STRICT_HTTPS: false
      DEBUG: true
      DEBUG_PORT: '*:9000'
      KC_LOG_LEVEL: info,au.org.raid.iam:debug,org.keycloak.services.cors:debug
  postgres:
    container_name: keycloak-postgres
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
