version: '3.4'
services:
  raid-iam-db:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
  raid-iam:
    depends_on:
      - raid-iam-db
#    image: 576003565477.dkr.ecr.ap-southeast-2.amazonaws.com/raid-iam:01c3803773b5d0b98ab76e87de37eec7071b060e
    build: .
#      dockerfile: ./Dockerfile
    ports:
      - 8001:8080
      - 9443:8443
      - 5005:5005
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 50
    command: [ 'start-dev', '--import-realm', '--debug' ]
    volumes:
      - './realms:/opt/keycloak/data/import'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: raid-iam-db
      KC_DB_URL_PORT: 5432
      KC_DB_SCHEMA: public
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      DEBUG: true
      DEBUG_PORT: '*:5005'
      KC_LOG_LEVEL: info,au.org.raid.iam:debug,org.keycloak.services:debug,org.keycloak.adapters:debug
#  nginx:
#    depends_on:
#      raid-iam:
#        condition: service_healthy
#    image: nginx:1.27.0-alpine
#    volumes:
#      - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#    ports:
#      - 8001:8001
