version: '3.4'
services:
  raid-iam-db:
    image: postgres:16.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      POSTGRES_DB: keycloak
  raid-iam:
    depends_on:
      - raid-iam-db
    build: .
    ports:
      - 8001:8080
      - 9443:8443
      - 5005:5005
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 5s
      timeout: 5s
      retries: 50
    command: [ 'start-dev', '--import-realm', '--debug' ]
    volumes:
      - './realms:/opt/keycloak/data/import'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: raid-iam-db
      KC_DB_URL_PORT: 5432
      KC_DB_SCHEMA: public
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
      DEBUG: true
      DEBUG_PORT: '*:5005'
      KC_LOG_LEVEL: info,au.org.raid.iam:debug,org.keycloak.services:debug,org.keycloak.adapters:debug
