name: app-client-ci
on:
  pull_request:
  push:
    branches:
    - main
    - v1.1
    paths-ignore:
      # don't need doc updates to do a rebuild, it's a waste of build minutes   
      - '**.md'
    
jobs:
  app-client-build:
    name: "app-client"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      # Corretto is the Raido standard JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'app-client/package-lock.json'          
      - name: run ci
        run: npm ci            
        working-directory: app-client
        
      - name: run build
        run: npm run build            
        working-directory: app-client
        
