name: CI
on: 
  push:
    paths-ignore:
      - '**.md'
jobs:
  build:
    runs-on: ubuntu-latest

# Not ready for this yet, need to have DB setup so tokens work, 
# don't wanna do import of prod data just for this.
# - flyway migrate - want to put raid_v1_import and api_svc schemas into single
#   project
# - need a way to bootstrap a token that the test can use    
#    
#    services:
#      postgres:
#        image: postgres:14
#        env:
#          POSTGRES_DB: postgres
#          POSTGRES_PASSWORD: postgres
#          POSTGRES_USER: postgres
#        ports:
#          - 5432:5432
#        # Set health checks to wait until postgres has started
#        options: >-
#          --health-cmd pg_isready
#          --health-interval 10s
#          --health-timeout 5s
#          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      # Corretto is the Raido standard JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      # https://github.com/gradle/gradle-build-action
      # setup and execute steps here were copied from readme
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle build
        run: ./gradlew build            

      # https://github.com/marketplace/actions/test-reporter
      - name: Reporting
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Junit Tests
          path: '**/build/test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: true