name: CI
on: 
  push:
    paths-ignore:
      # don't need doc updates to do a rebuild, it's a waste of build minutes   
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: raido
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      
      # Corretto is the Raido standard JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'corretto'

      # https://github.com/gradle/gradle-build-action
      # setup and execute steps here were copied from readme
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build and unit test
        run: ./gradlew build            

      - name: Create and populate file
        env:
          RAIDO_PG_URL: jdbc:postgresql://localhost:5432/raido
          RAIDO_PG_USER: postgres
          RAIDO_PG_PASSWORD: intTestPgPassword
        run: |
          cat <<EOF > ~/.config/raido-v2/api-svc-db.gradle
          apiSvcPgUrl="$RAIDO_PG_URL"
          apiSvcPgUser="$RAIDO_PG_USER"
          apiSvcPgPassword="$RAIDO_PG_PASSWORD"
          EOF

          echo "cat api-svc-db.gradle"
          cat ~/.config/raido-v2/api-svc-db.gradle

      - name: Create DB schemata
        run: ./gradlew flywayMigrate

      # https://github.com/marketplace/actions/test-reporter
      - name: Reporting
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Junit Tests
          path: '**/build/test-results/**/*.xml'
          reporter: java-junit
          fail-on-error: true